Startup script updates.

diff --git a/configs/etc/init.d/rc b/configs/etc/init.d/rc
--- a/configs/etc/init.d/rc
+++ b/configs/etc/init.d/rc
@@ -7,6 +7,23 @@ if [ -z '${RUNLEVEL}' ]; then
 	exit 1
 	fi
 
+start_services() {
+	RUNLEVEL=${1}
+	for SERVICE in /etc/rc${RUNLEVEL}.d/S* ; do
+		echo -n "Starting service ${SERVICE} ..."
+		${SERVICE} start 1>/dev/null 2>&1
+		STATUS=$?
+		if [ $STATUS -gt 0 ]; then 
+			echo "[FAILED ($STATUS)]"
+			else
+				echo "[OK]"
+			fi
+		done
+
+}	
+
+echo ""
+
 case ${RUNLEVEL} in 
 	0)
 	echo "Shutting down system ... "
@@ -14,18 +31,23 @@ case ${RUNLEVEL} in
 	;;
 	1)
 	echo "Entering runlevel ${RUNLEVEL} ... "
+	start_services 1 
 	;;
 	2)
 	echo "Entering runlevel ${RUNLEVEL} ... "
+	start_services 2 
 	;;
 	3)
 	echo "Entering runlevel ${RUNLEVEL} ... "
+	start_services 3 
 	;;
 	4)
 	echo "Entering runlevel ${RUNLEVEL} ... "
+	start_services 4 
 	;;
 	5)
 	echo "Entering runlevel ${RUNLEVEL} ... "
+	start_services 5
 	;;
 	6)
 	echo "Rebooting system ... "	
@@ -36,6 +58,7 @@ case ${RUNLEVEL} in
 	exit 1
 	;;
 esac
+echo ""
 
 exit 0
 
