Many much WIP.

diff --git a/configs/lib/lsb/init-functions b/configs/lib/lsb/init-functions
--- a/configs/lib/lsb/init-functions
+++ b/configs/lib/lsb/init-functions
@@ -811,5 +811,53 @@ log_daemon_msg()
 	echo "log_daemon_msg:" ${@}
 }
 
+################################################################################
+# log_daemon_msg()                                                             #
+#                                                                              #
+#                                                                              #
+################################################################################
+log_end_msg()
+{
+        echo "log_end_msg:" ${@}
+}
+
+################################################################################
+# status_of_proc()                                                             #
+#                                                                              #
+#                                                                              #
+################################################################################
+status_of_proc () 
+{ 
+    local pidfile daemon name status OPTIND;
+    pidfile=;
+    OPTIND=1;
+    while getopts p: opt; do
+        case "$opt" in 
+            p)
+                pidfile="$OPTARG"
+            ;;
+        esac;
+    done;
+    shift $(($OPTIND - 1));
+    if [ -n "$pidfile" ]; then
+        pidfile="-p $pidfile";
+    fi;
+    daemon="$1";
+    name="$2";
+    status="0";
+    pidofproc $pidfile $daemon > /dev/null || status="$?";
+    if [ "$status" = 0 ]; then
+        log_success_msg "$name is running";
+        return 0;
+    else
+        if [ "$status" = 4 ]; then
+            log_failure_msg "could not access PID file for $name";
+            return $status;
+        else
+            log_failure_msg "$name is not running";
+            return $status;
+        fi;
+    fi
+}
 
 # End /lib/lsb/init-functions
